export const demoResponse = [
  { id: 1, name: 'Welcome to Zoom Docs', creator: 'Omsai Nagvekar', lastViewed: '11 min ago' },
  { id: 2, name: 'My Zoom Meeting', creator: 'Omsai Nagvekar', lastViewed: '28 min ago' },
  { id: 3, name: 'Team Sync', creator: 'John Doe', lastViewed: '5 min ago' },
  { id: 4, name: 'Project Kickoff', creator: 'Jane Smith', lastViewed: '2 hr ago' },
    { id: 5, name: 'Product Roadmap', creator: 'Mark Johnson', lastViewed: '1 day ago' },
  { id: 6, name: 'Zoom Training', creator: 'Sarah Lee', lastViewed: '20 min ago' },
  { id: 7, name: 'Design Sprint', creator: 'Michael Brown', lastViewed: '3 hr ago' },
  { id: 8, name: 'Code Review', creator: 'Emily Davis', lastViewed: '15 min ago' },
  { id: 9, name: 'Marketing Strategy', creator: 'Jessica Harris', lastViewed: '30 min ago' },
  { id: 10, name: 'Sales Call', creator: 'David Clark', lastViewed: '1 hr ago' },
  { id: 11, name: 'Client Onboarding', creator: 'Patricia Walker', lastViewed: '45 min ago' },
  { id: 12, name: 'Budget Planning', creator: 'Chris Moore', lastViewed: '4 hr ago' },
  { id: 13, name: 'Product Launch', creator: 'Kimberly Taylor', lastViewed: '2 hr ago' },
    { id: 14, name: 'Staff Meeting', creator: 'James Anderson', lastViewed: '1 day ago' },
  { id: 15, name: 'Quarterly Review', creator: 'Robert White', lastViewed: '2 hr ago' },
  { id: 16, name: 'Customer Support Training', creator: 'Mary Adams', lastViewed: '12 min ago' },
  { id: 17, name: 'Tech Conference', creator: 'Patricia Baker', lastViewed: '3 hr ago' },
  { id: 18, name: 'Data Science Webinar', creator: 'Lucas Perez', lastViewed: '1 hr ago' },
  { id: 19, name: 'Weekly Standup', creator: 'Sandra Scott', lastViewed: '25 min ago' },
    { id: 20, name: 'Retrospective', creator: 'William Young', lastViewed: '1 day ago' },
  { id: 21, name: 'New Hire Orientation', creator: 'Olivia Nelson', lastViewed: '30 min ago' },
  { id: 22, name: 'Product Testing', creator: 'Joseph Carter', lastViewed: '2 hr ago' },
  { id: 23, name: 'Annual General Meeting', creator: 'Charlotte Mitchell', lastViewed: '4 hr ago' },
  { id: 24, name: 'SEO Strategy', creator: 'Sophia Robinson', lastViewed: '30 min ago' },
  { id: 25, name: 'User Feedback Session', creator: 'Benjamin Gonzalez', lastViewed: '1 hr ago' },
  { id: 26, name: 'Social Media Marketing', creator: 'Ethan Perez', lastViewed: '10 min ago' },
  { id: 27, name: 'Internal Training', creator: 'Mason Lewis', lastViewed: '3 hr ago' },
  { id: 28, name: 'Leadership Development', creator: 'Chloe Allen', lastViewed: '5 min ago' },
  { id: 29, name: 'Client Presentation', creator: 'Ava King', lastViewed: '2 hr ago' },
  { id: 30, name: 'Company Town Hall', creator: 'Liam Hall', lastViewed: '30 min ago' }
  ];