export const demoResponse = [
  { id: 1, name: 'Welcome to Zoom Docs', creator: 'You', lastViewed: '11 min ago' },
  { id: 2, name: 'My Zoom Meeting', creator: 'You', lastViewed: '28 min ago' },
  { id: 3, name: 'Team Sync', creator: 'You', lastViewed: '5 min ago' },
  { id: 4, name: 'Project Kickoff', creator: 'You', lastViewed: '2 hr ago' },
  { id: 5, name: 'Product Roadmap', creator: 'You', lastViewed: '1 day ago' },
  { id: 6, name: 'Zoom Training', creator: 'You', lastViewed: '20 min ago' },
  { id: 7, name: 'Design Sprint', creator: 'You', lastViewed: '3 hr ago' },
  { id: 8, name: 'Code Review', creator: 'You', lastViewed: '15 min ago' },
  { id: 9, name: 'Marketing Strategy', creator: 'You', lastViewed: '30 min ago' },
  { id: 10, name: 'Sales Call', creator: 'You', lastViewed: '1 hr ago' },
  { id: 11, name: 'Client Onboarding', creator: 'You', lastViewed: '45 min ago' },
  { id: 12, name: 'Budget Planning', creator: 'You', lastViewed: '4 hr ago' },
  { id: 13, name: 'Product Launch', creator: 'You', lastViewed: '2 hr ago' },
  { id: 14, name: 'Staff Meeting', creator: 'You', lastViewed: '1 day ago' },
  { id: 15, name: 'Quarterly Review', creator: 'You', lastViewed: '2 hr ago' },
  { id: 16, name: 'Customer Support Training', creator: 'You', lastViewed: '12 min ago' },
  { id: 17, name: 'Tech Conference', creator: 'You', lastViewed: '3 hr ago' },
  { id: 18, name: 'Data Science Webinar', creator: 'You', lastViewed: '1 hr ago' },
  { id: 19, name: 'Weekly Standup', creator: 'You', lastViewed: '25 min ago' },
  { id: 20, name: 'Retrospective', creator: 'You', lastViewed: '1 day ago' },
  { id: 21, name: 'New Hire Orientation', creator: 'You', lastViewed: '30 min ago' },
  { id: 22, name: 'Product Testing', creator: 'You', lastViewed: '2 hr ago' },
  { id: 23, name: 'Annual General Meeting', creator: 'You', lastViewed: '4 hr ago' },
  { id: 24, name: 'SEO Strategy', creator: 'You', lastViewed: '30 min ago' },
  { id: 25, name: 'User Feedback Session', creator: 'You', lastViewed: '1 hr ago' },
  { id: 26, name: 'Social Media Marketing', creator: 'You', lastViewed: '10 min ago' },
  { id: 27, name: 'Internal Training', creator: 'You', lastViewed: '3 hr ago' },
  { id: 28, name: 'Leadership Development', creator: 'You', lastViewed: '5 min ago' },
  { id: 29, name: 'Client Presentation', creator: 'You', lastViewed: '2 hr ago' },
  { id: 30, name: 'Company Town Hall', creator: 'You', lastViewed: '30 min ago' }
  ];